### ISSUE TITLE
Can you add option to wether auto deploy on save

### ISSUE THREAD

**Issue by artisticcheese** [mightycoco/fsdeploy#1]
Hi,

Is it possible to control deployment via save method to be optional. Sometimes you need to debug code locally and don't deploy it automatically on each save. 
Also does target supports UNC locations?

**Comment by mightycoco** [comment]
Hi,

UNC shares (on windows) are working as target and source. You have to escape backslashes: `\\\\server\\share\\folder\\target`

There will be a option in the next version to disable deploy on save:

"fsdeploy.deployOnSave": true|false

**Comment by artisticcheese** [comment]
Thanks. Can you please also elaborate where do I exactly put configuration file at for this extension to work.

**Comment by mightycoco** [comment]
Just put the settings in your user settings settings.json (File -> Prefererences -> User Settings)

**Comment by artisticcheese** [comment]
So this setting is per VScode installation as opposed to be per file? I expected to have configuration stored somewhere on file system where there is ".fs" file for each file on filesystem which identifies where file shall be deployed to.

**Comment by mightycoco** [comment]
Yes, this setting is a vscode setting (as it's a vscode extension) and no, there isn't a configuration file on disk per workspace.
