### ISSUE TITLE
Remove target-folder before deploy workspace (wish)

### ISSUE THREAD

**Issue by vicpuntnl** [mightycoco/fsdeploy#10]
This plugin does _almost_ exactly what I need! Thanks for that!

Only a minor thing is missing for my workflow: first remove the target folder before deploying the workspace. Is it possible to add this (under a feature-flag)?

**Comment by saschamander** [comment]
Added this feature to my Pull Request.
Auto deploy complete workspace / Remove target-folder before deploy workspace #12

**Comment by mightycoco** [comment]
added to base
