### ISSUE TITLE
Only works with Windows?

### ISSUE THREAD

**Issue by scottohara** [mightycoco/fsdeploy#2]
First up, let me just say I like where you're heading with this extension.

(I'm coming to vscode from vim, where I used a [similar plugin](https://github.com/cosminadrianpopescu/filesync) for copying files to a target directory automatically on save).

Unfortunately, I'm running vscode on a Mac, and it would seem that your extension is assuming Windows paths?

With a config like this:

``` javascript
{
   "fsdeploy.nodes": [
       {
          "source": "/Users/scott/src/",
          "target": "/Users/scott/dist/"
       }
   ],
   "fsdeploy.deployOnSave": true
}
```

...if I save a file `/Users/scott/src/foo.js` it gets deployed as `/Users/scott/dist/\\/Users/scott/src/foo.js`  (instead of `/Users/scott/dist/foo.js`)

It looks like in your `deploy()` function, you are hard coding Windows path separators (`\\`):

```
nodes.forEach((node: fsConfigNode) => {
  let subpath: string = path.substr(node.source.length);
  let target: string = `${node.target}\\${subpath}`;

  mkdirs(target);

  fs.copySync(filePath, `${target}\\${fileName}`);
 });
```

Any chance you could fix this so that it works cross-platform?

**Comment by mightycoco** [comment]
Hi scottohara,

you're right - that seems like a bad Idea. Need to take the node.js Path separator variable.

cheerz,
mc

**Comment by scottohara** [comment]
Tested new version, works perfectly.  Thanks for the quick turnaround.
