### ISSUE TITLE
Exclude multiple files option

### ISSUE THREAD

**Issue by alexfujita** [mightycoco/fsdeploy#4]
Hi there. Thanks for this nice and useful extension. I wanted to know if it is possible to setup an array of files inside of the exclude property.

Thanks in advance.

Alex

**Comment by mightycoco** [comment]
You can use the exclude option using the glob patterns to exclude single files.
More info: https://www.npmjs.com/package/glob

Example to exclude all files in /min/ subfolders and all jsunit.ts from all folders:
`exclude: "**/{min/*.*,jsunit.ts}"`

See this example: http://www.globtester.com/#p=eJzT0tKvzs3M09fS09LJKi7NyyzRyyquBQBLnwdF&r=eJxtzNENgyAUBdBVjAP4FkC26ACv%2BFohIAkXJXb6otUPU%2F9Pjhrs0hjPQN%2B2mh6QBBriW2iRtBIH%2FkjnoKg6ra54RiIfDXt62olKLP8qcDbjTrc3VJYF%2BTY8aeCqHObJ3ruTvKwX%2FLp8sC%2B4UkeR&
