### ISSUE TITLE
Does not support relative paths

### ISSUE THREAD

**Issue by greggbjensen** [mightycoco/fsdeploy#5]
After reviewing the code and trying it on Windows.  It appears it does not currently support relative paths.  Our team has different absolute paths and potentially drives on their machines.

I will be submitting a pull request shortly for this.

**Comment by greggbjensen** [comment]
@mightycoco it appears this project may not be monitored as much anymore.  I'm going to look into publishing this extension directly, so my team can use it.  Please let me know when your plugin is updated and I will be happy to switch.

**Comment by mightycoco** [comment]
What makes you think, the project is not monitored anymore?

**Comment by greggbjensen** [comment]
@mightycoco, sorry about that.  I just hadn't seen any response to the pull request and didn't notice any recent commits.  I would love to get this published if you are able.  It's really going to help our team out.

**Comment by greggbjensen** [comment]
@mightycoco It looks like you have had good success with 794 downloads for that plugin.  It looks like private extension repos are not yet supported, and I don't want to confuse the extension marketplace by publishing the extension again.  Do you know when you might be able to push a new version, or if there is a way for me to give a local copy to my team?

Thanks for your help,

Gregg

**Comment by greggbjensen** [comment]
@mightycoco no rush on this one.  I was able to find `mkloubert.vscode-deploy-reloaded` that does what I need.  I still think your extension is very useful as it is more specific and a bit easier to configure.  Best of luck.

**Comment by mightycoco** [comment]
I'm right now not able to test your code and recompile the plugin due to my personal situation. I'm back in business mid of april and will have a look at the code. Generally the push request looks good. I need to look up if the resolvePath doesn't affect absolute pathes, though.

**Comment by ciriousjoker** [comment]
Any news?

**Comment by mightycoco** [comment]
Merged e6ba78a to master
