### ISSUE TITLE
Can we have auto deply on reload of file.

### ISSUE THREAD

**Issue by himanshuporwal** [mightycoco/fsdeploy#7]
I am using this plugin and found it useful, but for one of the case I need to update the file again so that it gets deployed.

consider you are editing a file in different editor and the related project is already opened in visual code. When you switch to visual code the file gets reloaded with the changes but to deploy the file I again have to make some change and save it. 

Can this be handled?

**Comment by mightycoco** [comment]
Best options is using the deploy menu button on the QuickPick bar and select "Deploy File" or enter >fsdep and select "Deploy File"
