### ISSUE TITLE
Does Deploying a Single File Ignores The include/exclude Patterns?

### ISSUE THREAD

**Issue by jheanly** [mightycoco/fsdeploy#8]
I have just installed this extension to help me with some automatic php file deployment.

When saving a particular file, I only wanted one of the node patterns to be applied to this file (note, I have multiple nodes in my configuration). It seems that the automatic file deploy on save feature does not look at the include / exclude patterns when deploying a file. Is this correct? And if so, is this a conscious design decision?

I have a work-around by putting this particular file in it's own source directory. I was just wondering if the include/exclude could be applied when saving / deploying a single file?

**Comment by mightycoco** [comment]
yes, the single deployment of a file ignores include/exclude rules. 

I'll have a look into this. Not sure if I find a way, to match the glob pattern against a single input. You usually give this to a findFiles request when collecting the files.

**Comment by mightycoco** [comment]
Implemented in 3cc8ea74038b85b05b737dc1b12aea9e8d7f2cfc
Edit: version 0.1.10 having this commit is ready in the vsc market place
