### ISSUE TITLE
Add option to delete copied files if root file is deleted

### ISSUE THREAD

**Issue by mboegl** [mightycoco/fsdeploy#9]
I guess the title is kinda self explaining. Would be a great feature, but i have no clue if this is possible. It would be like like a raid 1.

**Comment by mightycoco** [comment]
With root file you mean source file? 

Currently I'm not keeping track of a history which files where transfered. I also don't browse the destination folder to see if something is there, which isn't available on the source folder. Doing this recursively could have performance impacts especially if the remote system is a network drive or an scp connection.

@saschamander implemented "Remove target-folder before deploy workspace" which could be a workaround for you. Always remove the entire target folder and do a full redeploy after changes. This only makes sense if you source and targets aren't too large, though.
